### ISSUE TITLE
[BE] CRUD movement classes

### ISSUE THREAD

**Issue by arthurgregorio** [web-budget/back-end#55]
Create all the flow to create, read, update and delete movement classes
```[tasklist]
### Tasks
- [ ] define entity and create migrations
- [ ] create controller and define contracts and validations
- [ ] create service and repository
- [ ] add tests
```
