### ISSUE TITLE
CRUD fixed movements

### ISSUE THREAD

**Issue by arthurgregorio** [web-budget/back-end#68]
```[tasklist]
### Tasks
- [ ] add rest controllers
- [ ] create flow to add them as period open
- [ ] create services and repositories
- [ ] add tests
```
